### ISSUE TITLE
401 (UNAUTHORIZED) example app

### ISSUE THREAD

**Issue by koreem** [PatrickHeneise/angular-digest-interceptor#11]
I get the following message when I want to login. I'm doing a 'GET' to ''http://httpbin.org/digest-auth/auth/user/passwd'' (user:passwd). Any idea why this isn't working?

<img width="434" alt="screen shot 2017-01-29 at 13 28 00" src="https://cloud.githubusercontent.com/assets/6543690/22403980/f0fb6b80-e626-11e6-9569-c1da1a022aad.png">

**Comment by PatrickHeneise** [comment]
Have you tried to authorise against the provided [server.js](https://github.com/PatrickHeneise/angular-digest-interceptor#serverjs)?

Apart from that I highly advise against digest authentication and would recommend [JWT](https://jwt.io) or oauth.
