### ISSUE TITLE
rejection.headers('WWW-Authenticate') returning null

### ISSUE THREAD

**Issue by shyamsathyanathan** [PatrickHeneise/angular-digest-interceptor#6]
When I run the application with the interceptor added it throws the following error:
    
    TypeError: Cannot read property 'match' of null
    at responseError (VM666 digest.js:39)
    at angular.js:14678
    at n.a.$get.n.$eval (angular.js:15922)
    at n.a.$get.n.$digest (angular.js:15733)
    at n.a.$get.n.$apply (angular.js:16030)
    at g (angular.js:10545)
    at K (angular.js:10717)
    at XMLHttpRequest.z.onload (angular.js:10658)

Using the debugger I found out that the value of <code>rejection.headers('WWW-Authenticate')</code> was null even though the server output header is 

    > HTTP/1.1 401 Full authentication is required to access this resource
    < Access-Control-Allow-Origin: *
    < Access-Control-Allow-Methods: POST, GET, PUT, OPTIONS, DELETE
    < Access-Control-Max-Age: 1800
    < Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
    < Cache-Control: no-cache, no-store, max-age=0, must-revalidate
    < Pragma: no-cache
    < Expires: 0
    < X-XSS-Protection: 1; mode=block
    < X-Frame-Options: DENY
    < X-Content-Type-Options: nosniff
    < WWW-Authenticate: Digest realm="XXXXXXX", qop="auth", nonce="MTQ0MzQyOTc2NDQ0MDplMjRiMTBiMThkZWMzZDgxZDI5YWZmZDNkNDFhZDNmZQ=="
    < Content-Type: text/html; charset=iso-8859-1
    * Server Development/1.0 is not blacklisted
    < Server: Development/1.0
    < Date: Mon, 28 Sep 2015 08:39:24 GMT
    < Content-Length: 195

This output was taken from curl tool.

**Comment by PatrickHeneise** [comment]
This was originally written for AngularJS 1.2.0 and hasn't been updated since. Do you have a suggestion how to solve the issue?

**Comment by iamambrus** [comment]
Shouldn't WWW-Authenticate be in Access-Control-Allow-Headers ?

**Comment by shyamsathyanathan** [comment]
@iamambrus Yes. I believe that was indeed what caused this. I'm closing this issue.
