### ISSUE TITLE
angular-localstorage or angular-local-storage?

### ISSUE THREAD

**Issue by brunofin** [PatrickHeneise/angular-digest-interceptor#7]
In the example [bower.json](https://github.com/PatrickHeneise/angular-digest-interceptor/blob/master/example/bower.json#L6) it says that I should use `angular-localstorage`, but npm can't find this package, giving this error `bower angular-localstorage#*              ENOTFOUND Package angular-localstorage not found`. Using `angular-local-storage` seems to work fine though, is this a typo or it's supposed to be like this?

Also, I would advise adding these dependencies to the project's `bower.json` file itself so npm can resolve them as it downloads `angular-digest-interceptor`, instead of letting the developer dig for them by itself.

**Comment by PatrickHeneise** [comment]
As far as I remember, the package used to be angular-localstorage. angular-local-storage should work though, it provides the same get and set functions

**Comment by brunofin** [comment]
Alright, thanks!
